### PR TITLE
fix snakeyaml error + temp remove metrics

### PR DESCRIPTION
**Pull request by crafter23456**
The reason for the snakeyaml push where of a buch of errors. These are now fixed. I tested it in 1.18, so I dont know if it makes problems to 1.17.1 currently.

I simply removed the metrics.
The reason for that was the building error: `/root/Git/Advanced-Slime-World-Manager/slimeworldmanager-plugin/src/main/java/com/grinderwolf/swm/plugin/SWMPlugin.java:118: error: constructor Metrics in class Metrics cannot be applied to given types;
new Metrics(this);`
To keep bstats we need something like:

```
private static final int BSTATS_ID = [ID];
Metrics metrics = new Metrics(this, BSTATS_ID);
```
I didnt found any bstats of ASWM anyways, so in fact it was the whole time useless, but with that code it should work when you make an ID. Therefore I keeped the bstats implementation.

### CODE REVIEW

**Comment by Paul19988** [comment]
Assuming bstats is useless was bold. ASWM falls under SWM for bstats.

**Comment by ComputerNerd100** [comment]
@crafter23456 Could you confirm your latest commit ("Add bstats back") is tested and works correctly on 1.18?

**Comment by crafter23456** [comment]
I dont know if bstats work now. But it builds, no errors in the minecraft log and I took the ID from SWM bstats.

**Comment by ComputerNerd100** [comment]
That's great - it building is a good sign!
We'll do the necessary testing during review. Thanks for the PR :)

**Review by Owen1212055 — APPROVED** [review]
Looks fine to me
